### ISSUE TITLE
BUG: `validate` function is called on blur when `validateOnBlur` is not specified/false

### ISSUE THREAD

**Issue by mdreyer** [wsmd/react-use-form-state#127]
**VERSION:** 0.12.1

**EXPECTED:** a field should only be validated on blur if `validateOnBlur` is true in its options

<img width="880" alt="wsmd_react-use-form-state__📄_React_hook_for_managing_forms_and_inputs_state" src="https://user-images.githubusercontent.com/1612961/75584011-a9f54480-5a23-11ea-8bbf-6f7574cc8b31.png">

**ACTUAL:** the field's `validate` function is always called on blur

**SETUP:**
```
const [formState, { text }] = useFormState();

return (
  <input
    {...text({
      name: 'someTextField',
      validate: (value, values, event) => {
        debugger;
      }
    })}
  />
)
```

or even:

```
const [formState, { text }] = useFormState();

return (
  <input
    {...text({
      name: 'someTextField',
      validateOnBlur: false,
      validate: (value, values, event) => {
        debugger;
      }
    })}
  />
)
```

...and when I blur that input the debugger is tripped, and confirmed the `event` parameter is specifying `type="blur"`

**Comment by wsmd** [comment]
Hi @mdreyer - thanks for opening the issue!

For context, `useFormState` was initially designed to run input validation on both `blur` and `change` events. Later on, `validateOnBlur` was introduced to prevent input validation on `change` and execute it only on `blur`. I understand that the description from the documentation you included above can be misleading. In reality, when `validateOnBlur` is set to `true`, the function will be called **only** when the input loses focus. Otherwise, it will be called on both `change` and `blur` events.

> EXPECTED: a field should only be validated on blur if validateOnBlur is true in its options

Changing this to what you expect is considered a breaking change (i.e. by default, validation is ran on both `blur` and `change`). That being said, since setting `validateOnBlur` to `false` is **obsolete** for the reason I discussed above, I believe respecting `false` as a possible value is a good solution to this issue.

**Comment by mdreyer** [comment]
@wsmd thank you for the clarification! that makes sense, I will expect validation to always be called on blur until that future release :) thanks again!
