### ISSUE TITLE
Values for input.checkbox other than strings

### ISSUE THREAD

**Issue by samholmes** [wsmd/react-use-form-state#14]
Looks like the only accepted value types for input.checkbox is a string value. Is there a reason for this? Could it be possible to support other values like numbers, objects, or arrays? If not, then maybe it should be documented that value must be a string and to recommend serializing values into a string before hand.

**Comment by wsmd** [comment]
Hello again, @samholmes!

> Is there a reason for this? Could it be possible to support other values like numbers, objects, or arrays?

Good question! I went back and forth on this; that is whether to serialize provided values or not. I ended up sticking to the DOM spec.

The value of the `value` attribute of a `<input type="checkbox">` is [expected to be a string](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Value) (a [`DOMString`](https://developer.mozilla.org/en-US/docs/Web/API/DOMString)).

React also treat values the same exact way: if you pass a `value` other than strings to a checkbox, the value you get back will be a string. I believe it's for the same reason above.

```jsx
<input
  type="checkbox"
  value={123} // non-string (also try objects, booleans, and arrays)
  onChange={e =>
    console.log({
      value: e.target.value, // value will be casted to a string
      type: typeof e.target.value // type will always be a string
    })
  }
/>

// logs: { value: "123", type: "string" }
```

For the same reason above, I don't believe it's possible to support non-string values.

My goal with react-use-form-state is to follow the same expectation. 

>  If not, then maybe it should be documented that value must be a string and to recommend serializing values into a string before hand.

This is documented in two places:

A) In the README.md under the "Input Types" section:

https://github.com/wsmd/react-use-form-state#input-types

B) It's also implicitly documented [in the type declaration file](https://github.com/wsmd/react-use-form-state/blob/14e3cd7d40294ecd2672e039f3897a0e3bb235fb/src/index.d.ts#L28-L36
) (if you use typescript)

![screen shot 2019-01-31 at 1 06 52 am](https://user-images.githubusercontent.com/2100222/52033872-8431ff00-24f4-11e9-8ccc-707be24ef3d3.png)

![screen shot 2019-01-31 at 1 19 10 am](https://user-images.githubusercontent.com/2100222/52034363-43d38080-24f6-11e9-8fc9-b84ab811f890.png)
 
---

I believe this answers your questions above. If it doesn't, please let me know! I'm close this issue for now, but that doesn't mean we have to stop talking about it! 😄

I might take casting non-string values provided to `input.checkbox` to strings into consideration in order to support the following (for convenience):

```jsx
<input {...input.checkbox('permissions', 4)} />
<input {...input.checkbox('permissions', 2)} />
<input {...input.checkbox('permissions', 1)} />

// Values in the outputted form state, however, would still have to be of type string!

{
  values: {
    permissions: ["4", "1", "2"]
  }
}
```

Can you provide a code example of what you are trying to achieve in your code? It'll help understand this better.

**Comment by samholmes** [comment]
I’d cast numbers to strings. I’d even cast objects to strings as well, but that doesn’t mean that the object should be serialize into a JSON strong. Maybe a simple .toString method call or new String(value) would suffice. All I know is that a lot of time was wasted trying to figure out why my code wasn’t working simply because I was using a number from my database as the value for the checkbox. The value was an ID of a record. It’s common to use numbers as values even HTML, however HTML will type cast to a string. This package should do the same IMO.

**Comment by wsmd** [comment]
`0.6.2`, now available on npm, added ability to use non-string values such numbers, booleans, objects, arrays to checkboxes and radio buttons as own values. These vales will be casted to strings.

```ts
<input {...input.checkbox('options', 'value')} />;
<input {...input.checkbox('options', true)} />;
<input {...input.checkbox('options', 123)} />;
<input {...input.checkbox('options', ['a', 'b'])} />;

{
  "values": {
    "options": [
      "value",
      "123",
      "a,b",
      "true"
    ]
  }
}
```

**Comment by samholmes** [comment]
Interesting solution. The only problem I have with this from a use-case point of view is that false becomes a truthy value ("false"). Not good.

I'd suggest using `JSON.stringify` on the value argument and put that in the element's value. Then when extracting the value out of the element, you could use `JSON.parse`. The only caveat is that the argument must be JSON "stringify-able", but this could be documented.
