### ISSUE TITLE
RFC: Add `id` to input props

### ISSUE THREAD

**Issue by jgierer12** [wsmd/react-use-form-state#17]
First off, amazing work on this library, it has now fully replaced Formik for me!

Do you think it would be a good idea (perhaps with an opt-out option) to also set the input's `id` to the same value as `name`? I find myself constantly having to add the `id` in order to make it work with `<label for="...">`. On the other hand, setting it automatically may clash with other `id`s the developer wants to use throughout the page.

An alternative solution would be to generate a randomized `id` and expose it as part of the `formState`, or as a third top-level return value from `useFormState()`.

If you think this would be a good addition I'd love to submit a PR for it.

**Comment by jgierer12** [comment]
To elaborate on my ideas a bit more, these are the different API possibilities I'm imagining:

```js
const [formState, inputs] = useFormState({ firstName: `John` });
// inputs.text(`firstName`).id = `firstName`

return (
  <>
    <label htmlFor="firstName">First Name</label>
    <input {...inputs.text(`firstName`)} />
  </>
);
```
```js
const [formState, inputs] = useFormState({ firstName: `John` });
// inputs.text(`firstName`).id = formState.ids.firstName = e.g. ___ufs-firstName

return (
  <>
    <label htmlFor={formState.ids.firstName}>First Name</label>
    <input {...inputs.text(`firstName`) />
  </>
);
```
```js
const [formState, inputs, id] = useFormState({ firstName: `John` });
// inputs.text(`firstName`) = id(`firstName`) = ___ufs-firstName

return (
  <>
    <label htmlFor={id(`firstName`)}
    <input {...inputs.text(`firstName`) />
  </>
);
```
I think I would mostly prefer the third one.

**Comment by wsmd** [comment]
> First off, amazing work on this library, it has now fully replaced Formik for me!

Woohoo! Thanks @jgierer12! It's truly humbling to hear that ☺️

I love this idea and I think it would be a great addition to the library. Working with the ids/labels has been a pain point for me too!

I appreciate the thorough examples you provided! I'm going to recap what you mentioned to make sure I fully understand the requirements that we need to make this happen.

### 1. Passing the `id` prop to the input

I think this can be very straightforward, assuming the the id will always be the input name:

```js
const [formState, inputs] = useFormState({ firstName: `John` });
inputs.text('firstName').id // → 'firstName'
```

But there's a catch 👇 

### 2. `id` for multiple inputs with the same name

This gets trickier when multiple inputs have the same name. For example, radio buttons, or checkboxes. For these inputs the name alone won't be enough:

```jsx
<>
  {/* how do we handle retrieving values of id/htmlFor when multiple inputs have the same name? */}
  <label htmlFor="???">Free</label>
  <input {...radio('plan', 'free')} />
  <label htmlFor="???">Premium</label>
  <input {...radio('plan', 'premium')} />
</>
```

Maybe we can account for the value as well... I'm not quite sure about that. 🤔 (more on randomized ids below)

This is one of my biggest questions I have about this introducing this addition.

### 3. Retrieving the `id` for the label

I like the third option you suggested! Since this library aims towards managing form state, I am not quite sure I'd consider the ids to be part of the state object itself. It's rather needed for rendering and it will likely be static.

I tend to think of the `formState` object as a way of communicating: _hey here's what you should know about how the user interacted with form_.

That said, exposing an `ids` object, on the other hand, feels more of an `opt-in` approach and doesn't impose itself if not needed.

```js
const [formState, inputs, id] = useFormState();
```

```jsx
<>
  <label htmlFor={id('firstName')}
  <input {...inputs.text('firstName') />
</>
```

I'd like to mindful about adding additional items to that array, and consider that option carefully as this library grows.

What happens when we keep adding to that array? Do we keep adding to that array? Since the order matter, it can be confusing to expect an array with more than 2-3 items. This is generally the case with function arguments; for example, many style-guides suggest using an object with named parameters if a function expects more than 3 arguments (e.g. `function doSomething(arg1, arg2, arg3, arg4)`).

I'd like to add another proposal to the ones you suggested above. What do you think of making use of the existing `inputs` object? To me, `id` is a rendering concern as much as `inputs` is. So what about adding another key to `inputs`?

I'm thinking something along these lines:

```jsx
const [formState, inputs] = useFormState();

<>
  <label {...inputs.label('foo')} />
  <input {...inputs.text('foo')} />
</>
```

And / Or

```jsx
<label htmlFor={inputs.id('foo')} />
```

More examples on this using destructuring:

```jsx
const [formState, { text, id, label }] = useFormState();

<>
  <label htmlFor={id('foo')} />
  <input {...text('foo')} />

  <label {...label('foo')} />
  <input {...text('foo') />
</>
```

### 4. Opt-out option

I feel comfortable making this a default behavior with an opt-out option like you mentioned. Maybe:

```js
const initialState = {
  firstName: 'John',
};

// it might worth considering having an options object this now as the library grows
const options = {
  withIds: false // to opt-out from generating ids
};

useFormState(initialState, options);
```

The reason I feel that this can be a default behavior (enabled by default) is that it could be easy to override the id even without opting-out via `options`, so you get the best of both worlds.

```jsx
// inputs.text('foo').id → "foo"
<input {...input.text('foo')} id="custom-id" />
```

### 5. Randomized Ids

Really interesting idea! It does raise some red flags though:

- Ids won't be predictable
- Because of that, testing becomes harder
- There's always the possibility of collision
- Though discouraged, such generated ids will be difficult to target for styling/css purposes.
- Lastly, it's probably an overkill

But hey, maybe we can let consumers of this library decide the format in which these ids will be generated! It's up to them if they want to randomize it! 🤷‍♂️ Give me some time to think about that 🤔 

---

Alright! that was a lot of info! I'm going to pin the issue, so let's keep the conversation going!

Please let me know what you think. Also, feel free to open a PR if you have something in the works. I'm also going to experiment with this very soon (hopefully this weekend).

**Comment by jgierer12** [comment]
Thanks! A lot of great ideas in there!

> Retrieving the `id` for the label

`inputs.label` and `inputs.id` sound great! I much prefer them to any of my ideas.

> Randomized Ids

We probably don't need random ids, I think it will be enough if we prefix them with a prefix like `__ufs__` so name `firstName` becomes id `__ufs__firstName`.

That should be very unlikely to clash with the user's own ids.

> `id` for multiple inputs with the same name

Good catch, I didn't think of that at all. What if we append the value in addition to the name:

```js
inputs.radio(`plan`, `free`).id === inputs.label(`plan`, `free`).id === `__ufs__plan__free`
```

Is there a case where multiple inputs can have the same name AND the same value?

---

I will start working on this now and try getting in a WIP PR later today.

**Comment by emlai** [comment]
> ```tsx
>   <label {...label('foo')} />
>   <input {...text('foo') />
> ```

+1. I like the uniformity here.

### 6. Return both `<label>` and `<input>`

I don't know if this has been already considered, but since you almost always want your inputs to have labels, wouldn't it make sense for the library to create the label+input pairs for you? For example:

```tsx
<>
  {text('fooBar')} // this would return both <label> and <input>
</>
```

The label text could be derived from the first argument: 'Foo bar'.
Or provided as an additional argument:

```tsx
<>
  {text('fooBar', 'custom label')}
</>
```

To omit the label:


```tsx
<>
  {text('fooBar', null)} // or '' instead of null
</>
```

This can be made backwards compatible by getting the `text` etc. properties from e.g. a `labeled` property in the inputs object:

```tsx
  const [formState, { labeled }] = useFormState();
  const { text } = labeled;
```

This would allow using the API also like this:

```tsx
<>
  {labeled.text('foo')}
</>
```

I understand this a bit more intrusive than just returning props. What do you think?

**Comment by jgierer12** [comment]
I think that would be a bit too much 'hand holding'. I very rarely have a case where

```js
<label htmlFor="name">Name</label>
<input type="text" id="name" ... />
```

is enough. Almost always I want to add my own props too, at the very least a `style`/`className`/`css`. I like the simplicity and unambiguity of the current API.

**Comment by emlai** [comment]
> Almost always I want to add my own props too, at the very least a `style`/`className`/`css`.

These could be passed through:

```tsx
<>
  {labeled.text('foo', { style: ..., className: ... })}
</>
```



> unambiguity

I agree. It's nice to see exactly which HTML elements are generated and have full control of them. Doing everything in the API would probably be a more framework-like approach, where actual components should be used instead of interpolated functions:

```tsx
<>
  <TextInput name='foo' className=... style=... /> // generates label and input
</>
```

`react-use-form-state` instead follows a more library-like approach where you only get the state management -related props from the API, so I think this idea would probably not be a good fit for `react-use-form-state`. Maybe as an opt-in alternative API but at that point you could create it as another library.

**Comment by wsmd** [comment]
> react-use-form-state instead follows a more library-like approach where you only get the state management -related props from the API

@emlai I would have said the same thing, but you beat me to it! 😄 

I also agree with @jgierer12, doing something like that makes this library somewhat opinionated, [which is not my goal](https://github.com/wsmd/react-use-form-state#motivation).
