### ISSUE TITLE
type safety for Inputs?

### ISSUE THREAD

**Issue by pocesar** [wsmd/react-use-form-state#27]
on large forms, it's easy to mess up when dealing with strings that are namespaced (like `address.street.lat`), would be nice that the `Inputs` declaration had a generic `Inputs<T>` so it can accept the name as being part of the "keyof T" in `useFormState`, so `[FormState<T>, Inputs]` -> `[FormState<T>, Inputs<T>]`

**Comment by wsmd** [comment]
Hi @pocesar,

I have considered that in the past, but I had an issue with, so I didn't end up implementing it. The problem is that `Inputs<T>` would prevent calling inputs with values that are not keys of `T`, which should technically be possible.

So for example, if I were to use something like `Inputs<T>` where the input name is `keyof T`, I'll run into this problem:

```ts
interface MyForm {
  username: string,
  password: string,
}

// passing type argument
const [formState, input] = useFormState<MyForm>();

input.text('username') // ok (type safe)
input.password('password') // ok (type safe)
input.checkbox('remember_me') // TYPE ERROR! (but should be allowed)
```

This is even a bigger problem with `initialState`, because `T` is also inferred from initial state if you are not explicitly passing the generic type argument.

```ts
const [formState, input] = useFormState({
  username: 'wsmd@example.com',
  password: '',
});

input.text('username') // ok (type safe)
input.password('password') // ok (type safe)
input.checkbox('remember_me') // TYPE ERROR! (but should be allowed)
```

Keep in mind that `keyof T` is a subtype of `string`, so it's not possible to use something like `keyof T | string`, as this will drop type safety for inputs, so we're back to square one.

That said, I agree that it would be great to have that type safety for input names.

There might be a work around to this, but I'm curious to hear your thoughts.

**Comment by wsmd** [comment]
@pocesar I published a new beta version to resolve this. Could you please give it a try by installing `react-use-form-state@0.7.0-beta.0`, and let me know if it doing what you would expect?

**Comment by pocesar** [comment]
I was just about to write about overloading the function but you beat me to it haha another way to do this would be using `Pick` (that's how React typings solves the problem with dynamic allocated state properties)

**Comment by wsmd** [comment]
Haha – i'm also interested in taking the `Pick` approach. How would that be helpful here? Feel free to comment on #28
