### ISSUE TITLE
About validate input validation function

### ISSUE THREAD

**Issue by romseguy** [wsmd/react-use-form-state#32]
`validate(value: string, values: StateValues): boolean`

> Optional. An input validation function that gets passed the input value and all input values in the state. It's expected to return a boolean indicating whether the input's value is valid. HTML5 validation rules are ignored when this function is specified.

I was interested in this function as a way to determine the origin of the validation error. Right now with a boolean flag it's not possible to distinguish.

Maybe extend the `validity` shape like so:

```
"validity": {
    "name": {
         someValidationRule: true|false,
         otherValidationRule: true|false
    }
}
```

Thank you for the great lib :)

**Comment by wsmd** [comment]
Thanks for the feedback @romseguy! 😄 

I'm planning on supporting custom validation errors in an upcoming release. Likely in 0.9.0. So I'm totally open to ideas.

I like your suggestion. It can be considered a breaking change though, since `validity.name` is expected to be truthy if the input valid. The object in your example will always be truthy whether the input is actually valid or not, so the following will break if it exists today:

```js
{touched.name && !validity.name && (
  <div className="error">Name is invalid!</div>
)}
```

I've been thinking about taking a very similar approach where the `validate()` function returns either `true` indicating the form is valid, or _any_ value other than `true` that will be treated as the error value and can be retrieved from `state.errors`. This should cover your use case above.

```js
input.text({
  name: 'name',
  validate: value => DISALLOWED_CHARS_REGEX.test(value)
    ? { foo: 'hello', bar: 'world' } // anything returned is a validation "error"
    : true,
  ),
});

{
  values: {
    name: 'wsm*$#d'
  },
  validity: {
    name: false,
  },
  errors: {
    name: {
      foo: 'hello',
      bar: 'world'
    },
  }
}

// this continues to work (you could still reference errors)
{touched.name && !validity.name && (
  <div className="error">Name is invalid!</div>
)}

// or you could check for the error itself
{touched.name && errors.name && (
  <div className="error">{errors.name.foo}</div>
)}
```

Stay tuned!

**Comment by romseguy** [comment]
Looks good to me :+1:

**Comment by KaRkY** [comment]
I would recommend the folowing API for usage with validation messages. 
```jsx
<div class="form-control">
  <label {...input.label("name")}>Email address</label>
  <input {...input.text("name")} />
  {input.valid("name") && <span input.valid("name") />}
</div>
```
