### ISSUE TITLE
npm update or install not updating

### ISSUE THREAD

**Issue by FabianoLothor** [wsmd/react-use-form-state#44]
`npm i -D react-use-form-state`

results
```bacth
+ react-use-form-state@0.4.0
updated 1 package and audited 37440 packages in 61.758s
found 63 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Not updating do v0.8.0.

**Comment by FabianoLothor** [comment]
`npm i -D react-use-form-state@0.8.0` forcing.

**Comment by wsmd** [comment]
@FabianoLothor What's your `package.json` like? 

If you are using an exact version, it won't update. You can read more about version ranges that you can specify in the `package.json` here https://docs.npmjs.com/files/package.json#dependencies

**Comment by wsmd** [comment]
Hi @FabianoLothor,

What's your `package.json` like? Without seeing it's hard to know what the issue is.

---

My guess is due to npm respecting semver. You are probably using `^0.4.0` at the time you installed this library (I believe npm defaults to `^`).

```json
"dependencies": {
  "react-use-form-state": "^0.4.0"
}
```

If that's case and that package isn't updating, that is by design as far as I know:


> [Caret ranges allow] changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple.

In this case, the left-most non-zero digit is `4`. Npm will not install anything `>= 0.4.x` because of that.

Once this library reached `1.0.0`, this won't be a problem, but that's going to take a while.

For the time being, you options are:

- **A)** Do exactly what you did [here](https://github.com/wsmd/react-use-form-state/issues/44#issuecomment-474820855)
- **B)** Update the `package.json` version to one of the following:
  - `"react-use-form-state": "<1.0.0"`(which would be my preference, since i've been mindful not introducing any breaking changes prior to `1.0.0`)
  - `"react-use-form-state": "0.x"`. 
  - `"react-use-form-state": ">=0.4"`.

**You can ready more about these here:**
- https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
- https://docs.npmjs.com/files/package.json#dependencies

**Comment by FabianoLothor** [comment]
I see, thanks for the help! :)
