### ISSUE TITLE
Setting state values manually

### ISSUE THREAD

**Issue by hcavalieri** [wsmd/react-use-form-state#52]
First of all, thanks **a lot** for this amazing work, @wsmd ! Huge time saver, very performant and _extremely_ clean API, you really nailed it 😄

The only issue I have with this hook is the fact that you only pass down [`formState.current`](https://github.com/wsmd/react-use-form-state/blob/master/src/useFormState.js#L198) through the hook, meaning we're locked if we need to set state manually.

I'm creating a form in which I ask for an URL, fetch its meta title via a cloud function and then return it to automatically add it to the `title` input (which can also be edited by the user). I can run the `fetchUrl` through the `onBlur` option inside the URL input, but then I have no means of updating the title inside `formState` 😔

Is there any way we could return the whole `formState` object (in v.1) in the hook or is it too dangerous / wouldn't work? It'd be something like this:

```js
// inside useFormState.js
return [
    formState,
    {
      ...inputPropsCreators,
      [LABEL]: (name, ownValue) => getIdProp('htmlFor', name, ownValue),
    },
  ];

// inside YourComponentForm.jsx
const [{ current, setValues }, input] = useFormState()
```

For the time being, I'll manage the title input outside of useFormState, unfortunately 😭

**Comment by stclairdaniel** [comment]
This is something our team needs as well - sometimes we'll have a field that strictly determines the value of another field, and I'd like to be able to set it manually.

**Comment by wsmd** [comment]
Hi @hcavalieri, Thanks a lot! 😊 

> The only issue I have with this hook is the fact that you only pass down formState.current through the hook, meaning we're locked if we need to set state manually.

Out of curiosity, how would retuning something other than `formState.current` help in your situation? While I understand the limitation of not being able to set a value manually, I don't understand how that is an issue caused by that fact that I'm passing `formState.current`.

That said, the only challenge I keep facing up when I think about manually updating a value is handling validity, touched, etc. For example, **validating an input requires access to the underlying DOM node** since it's fired on both the `blur` and `change` event and requires access to the event target.

The only option I think of right now is adding a `input.forceUpdate(name, value)` method that allows the developer to set the value programmatically with only one caveat: **it has to skip validation. It's up to the developer to ensure the value being set is valid**! Maybe we can run the value through the same validation criteria you're expecting your users to respect. 

The more I think about this, the more I feel comfortable with skipping validity, touched, and error states – the value is set programmatically after all, and you are probably using the validity/touched/error state to display some validation errors to your users. If the value is set programmatically is invalid, and I somehow managed to validate the value using `forceUpdate`, that will leave users confused. 

So, a simple example of this would be:

```jsx
function App() {
  const [formState, input] = useFormState();

  const onPageChange = React.useCallback(async e => {
    if (e.target.validity.valid) {
      const meta = await myFakeAPI.getPageMeta(e.target.value);
      // manually updating an input value
      input.forceUpdate('title', meta.title);
    }
  });

  return (
    <form>
      <input {...input.url({ name: 'page', onChange: onPageChange })} />
      <input {...input.text('title')} />
    </form>
  );
}
```

<img width="502" src="https://user-images.githubusercontent.com/2100222/56003108-2c053f00-5c93-11e9-87da-8cdb1a20a91e.gif" />


What do you think?

**Comment by DarrylD** [comment]
can something this work:
```javascript
const values = {name: 'bob', age: 10} //lets say we have 20 fields...
input.forceUpdates(values);
```

Thinking of the cases where many fields needs to be updated (my current case).

**Comment by hcavalieri** [comment]
Thanks for the quick and thorough answer, @wsmd !

This works perfectly for my use case - in fact, your example was my challenge itself 😝 - but I'm not sure about other people's... For @DarrylD 's case, I believe a simple `for` loop would do it, and then React could batch-render the state updates - there shouldn't happen a drop in performance.

I didn't go through your whole API, Waseem, but if this change doesn't incur into conflict and still helps @stclairdaniel and others, it's a big thumbs up for me 👍 Thanks for the solution, btw, I agree with 100% of your thought process 💃

**Comment by DarrylD** [comment]
>For @DarrylD 's case, I believe a simple for loop would do it, and then React could batch-render the state updates - there shouldn't happen a drop in performance.

While I agree, I do believe this will be a common thing, amung users. If everyone is doing the same looping, might be a good idea to just bake it in.

I think to clear the entire form (think of clearing upon adding something) with this approach may also be a good use case. 

Just my 2cents, overall love the idea of the project! My only deal breaker is no simple way to clear/change the values in bulk.

**Comment by hcavalieri** [comment]
You're absolutely right, Darryl! I didn't think of clearing the form and, indeed, updating multiple values is a common use case...

`forceUpdate` could have an internal type checking that, if you pass down 2 arguments - the first being a string and the second a value - then it'd update the named property, else, if you pass down an object, it'd loop through `Object.keys` and update each of them accordingly. However, this approach doesn't cover clearing the form quite well: would we need to pass down an object with all keys but empty values?

**Comment by DarrylD** [comment]
>would we need to pass down an object with all keys but empty values?
that should be fine!

**Comment by julianux** [comment]
Hey guys, a newbie here, how are you cleaning the form after submit? I have an issue with that :(

**Comment by wsmd** [comment]
Thanks for the feedback, everyone! 

You'll be able to set values of input values manually in the next release `0.10.0` which will be published very soon! 🎉 

Unfortunately, I won't be supporting setting multiple values at once. **However, there will be a new method to clear the entire form** since that's probably the most common use-case for bulk update from what I've seen in this discussion. 

The reason I won't be including bulk update is because of the added complexity it brings to the library - it will be a maintenance burden eventually, and removing features is far more harder than adding them 😄. The goal with this library is to keep it simple yet flexible enough to allow the developers to do whatever they want. If bulk update is truly necessary a small `Object.keys` or `for..in` loop should do the trick.

Thanks!

**Comment by melloc01** [comment]
That's great, thanks @wsmd!

I was hoping for this to be released so I could use on my "ArrayField" use case that received new props and had to set input states accordingly.

Although I think this was really missing feature, I think a declarative way would be a better a approach, what do you think? We could achieve that by having a two-way data-bind on the value prop, just like a normal input:

```js
<input {...inputs.text('name')} value={props.name} />
```

if `props.name` changes, the form state field also does - sorry I didn't have time to look at the source code, not sure how much that'd impact or if it is even feasible, just brainstorming here.
