### ISSUE TITLE
[bug] setField() doesn't invoke formState's onChange() method 

### ISSUE THREAD

**Issue by vovanezha** [wsmd/react-use-form-state#77]
I try to update field manually and subscribe to onChange() method in formState object, but after I apply setField() the values of formState iteself is changing and onChange() doesn't executes

```javascript
const [formState, { text, radio, label }] = useFormState<IProfilesFilter>(params, {
    onChange(
      event: React.ChangeEvent<InputElement>,
      old: StateValues<IProfilesFilter>,
      newValues: StateValues<IProfilesFilter>,
    ) {
      event.preventDefault();
      console.log(newValues);
    },
  });

  const handleSelect = (newValue: string): void => {
    formState.setField("selected", [...selectedItems, newValue]);
  };
```

**Comment by wsmd** [comment]
Hi @vovanezha,

the form option onChange only works with changes coming from the user interacting with your form, not changes triggered programmatically by you which mutate the state of the form directly.

For example, in your code above, the code will throw an error if we were to trigger `onChange` after calling `setField` because we do not have access to the input change event - there is none.

```ts
const [formState, { text, radio, label }] = useFormState<IProfilesFilter(params, {
  onChange(
    event: React.ChangeEvent<InputElement>,
    old: StateValues<IProfilesFilter>,
    newValues: StateValues<IProfilesFilter>,
  ) {
    // this will throw an error if we were to trigger onChange after calling
    // setField because it's does not have a change event.
    event.preventDefault();
  },
})
```

That said, based on this snippet:

```ts
const handleSelect = (newValue: string): void => {
  formState.setField("selected", [...selectedItems, newValue]);
};
```

It looks like you are trying to set a custom value in the from. Have you considered using a `raw` input instead? https://github.com/wsmd/react-use-form-state#custom-controls

I hope that helps. Don't hesitate to reach out if you have any questions!
