### ISSUE TITLE
useCache generate a new Map everytime it's ran

### ISSUE THREAD

**Issue by pocesar** [wsmd/react-use-form-state#80]
this part of the code https://github.com/wsmd/react-use-form-state/blob/master/src/useCache.js#L4

should be using `useMemo` instead with some mechanism for busting itself. this library already makes a lot of useless re-renders, it should start focusing on optimizing the code

**Comment by wsmd** [comment]
Hi @pocesar - there was a temporary issue with caching in `0.10.1` that was fixed in the latest version yesterday, please make sure you are on `0.10.2`.

It's worth noting that the caching issue you are seeing isn't with the map itself. In fact, `useRef` doesn't create a new map on every re-render:

https://reactjs.org/docs/hooks-reference.html#useref

> useRef returns a mutable ref object whose .current property is initialized to the passed argument (initialValue). _The returned object will persist for the full lifetime of the component_.

Here's in a example to demonstrate the performance of this library: https://yq1l6185ox.codesandbox.io/

Please make sure you are on the latest version and if you are still having any issue, post a comment here to let me know (and preferably with a code example) and I'll be happy to re-open this issue.

**Comment by pocesar** [comment]
yeah, I'm using the latest version, but that's not what I meant. the "new Map()" is eagerly executed, and not lazily like in:
```jsx
const state = useState(() => {
  return { some: 'initialState' }
})

const memoized = useMemo(() => {
  return new Map()
}, [])
```

the way code is created in this library seems to not deal with ref stability (for functions, objects, etc). this is a constructive criticism, that should focus on optimizations. [spread props is already bad by itself](https://github.com/yannickcr/eslint-plugin-react/issues/1094) and is the main drive of this hook.
when using hooks from other people, we expect that the refs are stable, like here https://github.com/kitze/react-hanger/blob/master/src/useInput.ts#L19

**Comment by adjourn** [comment]
@wsmd VERY helpful example demonstrating the performance. I'm glad I didn't have to spend several hours to test it myself, now I'm confident that I'll pick this package for all my forms. 

I suggest to add it to README if it's not there yet. Thank you for this great hook.
